---
- name: Install Apache
  ansible.builtin.package:
    name: apache2  # Use 'httpd' for CentOS/RHEL
    state: present

- name: Start and enable Apache
  ansible.builtin.service:
    name: apache2  # Use 'httpd' for CentOS/RHEL
    state: started
    enabled: yes

- name: Create document root directory
  ansible.builtin.file:
    path: /var/www/html
    state: directory

- name: Deploy sample PHP application
  ansible.builtin.copy:
    content: |
      <?php
      $conn = new mysqli("192.168.56.102", "user", "password", "mydatabase");
      if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
      }
      echo "Connected successfully";
      ?>
    dest: /var/www/html/index.php
    owner: www-data
    group: www-data
    mode: '0755'
